name: nullface
dependencies:
  - python=3.12
  - pip
  - pip:
    - diffusers[torch]==0.30.0
    - transformers >=4.44.0,<=4.51.3
    - torchvision >=0.19.0,<=0.21.0
    - datasets >=3.0.1,<=3.5.0
    - opencv-python >=4.10.0.84,<=4.11.0.86
    - insightface==0.7.3
    - onnxruntime-gpu >=1.18.1,<=1.21.0
    - peft >=0.12.0,<=0.15.2
    - face-alignment==1.4.1
